In [30]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

Numpyのレッスン

In [31]:
import numpy as np

一次元配列

In [32]:
# リストを読み込んで1次元numpy arrayを生成
n1array = np.array([1, 2, 3, 4, 5])

In [33]:
n1array

array([1, 2, 3, 4, 5])

In [34]:
print(n1array)

[1 2 3 4 5]


In [35]:
type(n1array)

numpy.ndarray

In [36]:
n1array.shape

(5,)

二次元配列

In [37]:
# 2次元リストを読み込んで2次元numpy arrayを生成
n2array = np.array([[1, 2, 3], [4, 5, 6]])

In [38]:
n2array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
print(n2array)

[[1 2 3]
 [4 5 6]]


In [40]:
n2array.shape

(2, 3)

行列の変形

In [47]:
na1 = np.array([0, 1, 2, 3, 4, 5])
na1

array([0, 1, 2, 3, 4, 5])

In [50]:
na2 = na1.reshape(2, 3)
na2

array([[0, 1, 2],
       [3, 4, 5]])